version: '3'
services:
  jupyter_ryeleussinov:
    image: jupyter/all-spark-notebook
    volumes:
      - /home/ryeleussinov/src/config/workspace:/home/jovyan/work
      - conda_env:/opt/conda
    ports:
      - "8887:8888"
  
volumes:
  conda_env:
    external: true
      
  # jupyter_temirlan:
  #   image: jupyter/all-spark-notebook
  #   volumes:
  #     - /home/temirlan:/home/jovyan/work
  #   ports:
  #     - "<new_port2>:8888"
